apiVersion: apps/v1
kind: Deployment
metadata:
  name: microfrontend-backend-deployment
  labels:
    app: microfrontend-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microfrontend-backend
  template:
    metadata:
      labels:
        app: microfrontend-backend
    spec:
      containers:
      - name: microfrontend-backend
        image: microfrontend-backend
        ports:
        - containerPort: 5000
