apiVersion: apps/v1
kind: Deployment
metadata:
  name: microfrontend-backend-deployment
  labels:
    app: microfrontend-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microfrontend-backend
  template:
    metadata:
      labels:
        app: microfrontend-backend
    spec:
      containers:
      - name: microfrontend-backend
        image: fareeboy12/microfrontend-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: microfrontend-backend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000