apiVersion: apps/v1
kind: Deployment
metadata:
  name: microfrontend-storeone-deployment
  labels:
    app: microfrontend-storeone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microfrontend-storeone
  template:
    metadata:
      labels:
        app: microfrontend-storeone
    spec:
      containers:
      - name: microfrontend-storeone
        image: fareeboy12/microfrontend-storeone
        imagePullPolicy: Always
        ports:
        - containerPort: 3006
---
apiVersion: v1
kind: Service
metadata:
  name: storeone-service
spec:
  selector:
    app: microfrontend-storeone
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3006
      targetPort: 3006
      nodePort: 30083